### ISSUE TITLE
Passing Empty Query String Returns Actual Data In Front End

### ISSUE THREAD

**Issue by pappyJ** [ijemmao/igbo_api#205]
While this might be good for d Api to return all d words in the DB . I don't Think it is  a good feature for d front end . i headed over [our inspiration website](https://jisho.org/) to confirm and it handles this action very differently
![Screenshot from 2020-10-30 01-46-38](https://user-images.githubusercontent.com/65920240/97647627-06957d00-1a53-11eb-942c-8754b3ef4105.png)

**Comment by ijemmao** [comment]
So the API homepage and the dictionary front-site serve two different purposes:

* The API homepage is meant for developers who want a quick introduction to the API and its features without having to set up a project that consumes the API. A good example of this happening would be the [WordsAPI](http://wordsapi.com/)
* The dictionary front-site is for everyone else who wants to use a product that consumes the API. That's why you don't see the raw API response for that site.

With this, do you think we still shouldn't show the raw data from the database?

**Comment by pappyJ** [comment]
Seen .. But Even in [WordsApi](http://wordsapi.com/) A New Http Request Is Not Made Once The Input Form Is Empty

**Comment by ijemmao** [comment]
I see what you mean. Yeah, this is a current implementation detail that needs to be addressed.

What should happen is when an empty request is made then an error is return back to the client saying that they must enter in some text. This change hasn't been a top priority for development, but is something that will be addressed in the future. I'll create a new ticket to track this.

**Comment by pappyJ** [comment]
Once I'm through with cors implementation I'll take it up

**Comment by pappyJ** [comment]
Can I take this???

**Comment by ijemmao** [comment]
One thing that you need to consider is that we keep the current state of return the first ten results when there's no `keyword` query provided when in a development environment AND when the requesting user either an editor, merger, or admin.

In other words, we want to return an empty array of results when no `keyword` query is provided and if the requesting client is a regular `user` or just unauthed.

**Comment by pappyJ** [comment]
Noted ma'am
